#pragma once
#include "Headers.h"

#pragma region Images
#define BACKGROUND_PATH "./assets/sprites/background/background_7.png"
#define BACKGROUND_LOGO_PATH "./assets/sprites/background/bg_orange.png"
#define BACKGROUND_CREDITS_PATH "./assets/sprites/background/bg_lightblue.png"
#define BACKGROUND_INSTRUCTIONS_PATH "./assets/sprites/background/bg_lightgreen.png"
#define BACKGROUND_GAME_INITIALIZER_PATH "./assets/sprites/background/bg_game_initializer.png"
#define BACKGROUND_EXIT_PATH "./assets/sprites/background/bg_game_exit.png"
#define BACKGROUND_GAME_AFTERNOON "./assets/sprites/background/background_map_afternoon.png"
#define BACKGROUND_GAME_NIGHT "./assets/sprites/background/background_map_night.png"
#define TITLE_PATH "./assets/sprites/logo/title.png"
#define LOGO_PATH "./assets/sprites/logo/logo.png"
#define BUTTON_PATH "./assets/sprites/buttons/button.png"
#define INSTRUCTIONS_MOVE_FARMER_PATH "./assets/sprites/instructions/farmer_instructions.png"
#define ANIMALS_MOVE_PATH "./assets/sprites/instructions/farmer_instructions.png"
#define ENEMIGES_PATH "./assets/sprites/instructions/enemiges.png"
#define FARMER_HUD "./assets/sprites/instructions/farmer_hud.png"
#define FARMER_KEYS_PATH "./assets/sprites/instructions/farmer_keys.png"
#define INSTRUCTIONS_MOVE_FARMER_PATH "./assets/sprites/instructions/farmer_instructions.png"
#define EXIT_ANIMATION_PATH "./assets/sprites/exit/exit_animation.png"
#define GAEL_ANIMATION_PATH "./assets/sprites/credits/gael.png"
#define ALEJANDRO_ANIMATION_PATH "./assets/sprites/credits/alejandro.png"
#define MARIA_FE_ANIMATION_PATH "./assets/sprites/credits/maria_fe.png"
#define SLOT_PATH "./assets/sprites/game/slot.png"
#define SLOT_MENU_PATH "./assets/sprites/game/slot_menu.png"
#define SLOT_DIFFICULT_PATH "./assets/sprites/game/slot_difficult.png"
#define BG_GAME_FINISH "./assets/sprites/background/bg_game_finish.png"
#define SCARECROW_PATH "./assets/sprites/game/scarecrow.png"
#define SELL_PLACE_PATH "./assets/sprites/game/sell_place.png"
#define SHOP_PATH "./assets/sprites/game/shop.png"
#define INDICATOR_PATH "./assets/sprites/game/indicator.png"
#define	FRAMER_SPRITESHEET "./assets/sprites/game/farmer.png"
#define RABBIT_SPRITESHEET "./assets/sprites/animals/rabbit/spritesheet.png"
#define RACCOON_SPRITESHEET "./assets/sprites/animals/raccoon/spritesheet.png"
#define MOLE_SPRITESHEET "./assets/sprites/animals/mole/spritesheet.png"
#define DOG_SPRITESHEET "./assets/sprites/animals/dog/spritesheet.png"
#define BAT_SPRITESHEET "./assets/sprites/animals/bat/spritesheet.png"
#define SHOP_VEGETABLE_PATH "./assets/sprites/game/shop_vegetable.png"
#define TOMATO_SEED "./assets/sprites/vegetables/tomato/seed.png"
#define TOMATO_PLANT "./assets/sprites/vegetables/tomato/plant.png"
#define TOMATO_HARVEST "./assets/sprites/vegetables/tomato/harvest.png"
#define CARROT_SEED "./assets/sprites/vegetables/carrot/seed.png"
#define CARROT_PLANT "./assets/sprites/vegetables/carrot/plant.png"
#define CARROT_HARVEST "./assets/sprites/vegetables/carrot/harvest.png"
#define WHEAT_SEED "./assets/sprites/vegetables/wheat/seed.png"
#define WHEAT_PLANT "./assets/sprites/vegetables/wheat/plant.png"
#define WHEAT_HARVEST "./assets/sprites/vegetables/wheat/harvest.png"
#define PUMPKIN_SEED "./assets/sprites/vegetables/pumpkin/seed.png"
#define PUMPKIN_PLANT "./assets/sprites/vegetables/pumpkin/plant.png"
#define PUMPKIN_HARVEST "./assets/sprites/vegetables/pumpkin/harvest.png"
#define INDICATOR_SUN_PATH "./assets/sprites/game/sun.png"
#define INDICATOR_MOON_PATH "./assets/sprites/game/moon.png"
#define FARMER_ALLIED_PATH "./assets/sprites/game/farmer_allied.png"
#define COIN_PATH "./assets/sprites/game/coin.png"
#define COIN_ANIMATE_PATH "./assets/sprites/game/coin_animate.png"
#define LIGHT_PATH "./assets/sprites/game/light.png"
#define POT_PATH "./assets/sprites/game/pot.png"
#define FENCE_PATH "./assets/sprites/game/fence.png"
#define BUBBLE_PATH "./assets/sprites/game/bubble.png"
#define BAR_TIME_MATHEMATICS_PATH "./assets/sprites/game/bar_time_mathematics.png"
#define KEY_E_PATH "./assets/sprites/game/e.png"
#define KEY_Q_PATH "./assets/sprites/game/q.png"
#define FILE_SAVED_PATH "./data/data.dat"
#pragma endregion

#pragma region Fonts
#define FONTS_PATH "./assets/fonts/Big Apple 3PM.ttf"
#pragma endregion

#pragma region Sounds
#define BUTTON_HOVER_SOUND_PATH "./assets/sounds/effects/hover_button.wav"
#define BUTTON_CLICK_SOUND_PATH "./assets/sounds/effects/click_button.wav"
#pragma endregion

